import { useLocation, useNavigate } from "react-router-dom";

const Report = () => {
  const location = useLocation();
  const navigate = useNavigate();

  const downloadReport = () => {
  const percentage = Math.round(result.similarity_score * 100);

  const reportContent = `
CODE SIMILARITY REPORT
----------------------

File 1 : ${result.file1_name || "File1"}
File 2 : ${result.file2_name || "File2"}

Similarity Score : ${percentage}%
Verdict : ${result.verdict}

Generated At : ${new Date().toLocaleString()}

Analysis Method:
AST-based similarity detection.

--------------------------------
Generated by Code Similarity Analyzer
`;

  const blob = new Blob([reportContent], { type: "text/plain" });

  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "similarity_report.txt";

  link.click();
};

  const result =
    location.state || JSON.parse(localStorage.getItem("reportData"));

  if (!result) {
    return (
      <div className="text-center mt-20 text-gray-300">
        No report data available.
      </div>
    );
  }

  const percentage = Math.round(result.similarity_score * 100);

  return (
    <div className="max-w-4xl mx-auto py-16 px-6">

      <h1 className="text-4xl font-bold text-center mb-12 bg-gradient-to-r from-cyan-400 to-purple-500 bg-clip-text text-transparent">
        Similarity Report
      </h1>

      <div className="backdrop-blur-lg bg-white/10 border border-white/20 rounded-2xl p-10 shadow-2xl space-y-8">

        <div>
          <h2 className="text-2xl font-semibold mb-4">Similarity Score</h2>

          <div className="w-full bg-white/10 rounded-full h-8 overflow-hidden border border-white/20">
            <div
              className="h-full flex items-center justify-end pr-4 text-sm font-bold text-white transition-all duration-1000 bg-gradient-to-r from-cyan-500 to-purple-600"
              style={{ width: `${percentage}%` }}
            >
              {percentage}%
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-semibold mb-4">Verdict</h2>
          <span className="px-6 py-3 rounded-full bg-gradient-to-r from-purple-500 to-indigo-600 text-white font-bold">
            {result.verdict}
          </span>
        </div>

        <div className="grid md:grid-cols-2 gap-6 pt-6 border-t border-white/20">
          <div className="bg-white/5 p-6 rounded-xl">
            <h3 className="font-semibold text-lg mb-2">File 1</h3>
            <p className="text-gray-300">{result.file1_name}</p>
          </div>

          <div className="bg-white/5 p-6 rounded-xl">
            <h3 className="font-semibold text-lg mb-2">File 2</h3>
            <p className="text-gray-300">{result.file2_name}</p>
          </div>
        </div>

        <div className="text-center pt-8">
          <button
            onClick={downloadReport}
            className="mr-4 px-8 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 hover:scale-105 transition shadow-lg text-lg font-semibold"
          >
            Download Report
          </button>
          <button
            onClick={() => navigate("/compare")}
            className="px-8 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 hover:scale-105 transition shadow-lg text-lg font-semibold"
          >
            Compare Again
          </button>
          
        </div>

      </div>

    </div>
  );
};

export default Report;