from datetime import datetime

def generate_report(result: dict) -> str:
    """
    Generate a formatted similarity report string.
    """

    similarity_score = round(result.get("similarity_score", 0) * 100, 2)
    verdict = result.get("verdict", "Unknown")

    file1 = result.get("file1_name", "File1")
    file2 = result.get("file2_name", "File2")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""
CODE SIMILARITY ANALYSIS REPORT
--------------------------------

File 1: {file1}
File 2: {file2}

Similarity Score: {similarity_score} %
Verdict: {verdict}

Generated On: {timestamp}

Analysis Method:
Abstract Syntax Tree (AST) comparison

Description:
This analysis compares the structural representation
of the source code rather than raw text. It helps detect
logical similarity even if variable names or formatting
are changed.

--------------------------------
Generated by Code Similarity Analyzer
"""

    return report


def save_report(result: dict, filename="similarity_report.txt"):
    """
    Save the generated report to a file.
    """

    report_text = generate_report(result)

    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_text)

    return filename